# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target "YOUR_TARGET_NAME" do
    pod 'JumioMobileSDK', '2.10.0'
end
