# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target "YOUR_TARGET_NAME" do
    pod 'JumioMobileSDK', '3.1.0'
end
