# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'http://mobile-sdk.jumio.com/distribution.git'

use_frameworks!

target "DemoApp" do
    pod 'JumioMobileSDK-FAT', '2.9.0'
end
